project:
  type: website
  output-dir: docs

website:
  title: "[Muhammed Uğur Çubuk]'s Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/mugurcubuk
      - icon: twitter
        href: https://x.com/on2nci
      - icon: linkedin
        href: https://www.linkedin.com/in/muhammed-u%C4%9Fur-%C3%A7ubuk-53a55b254/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU430 - 2024 Fall" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme:
      light: cosmo
      dark: superhero
    css: styles.css


