---
title: "Assignment 1"
---

# Assignment 1

# **a)**

I watched the video where Mustafa Gökçe Baydoğan was a guest.

In this video, Mr. Baydoğan explained data analytics and applications in the field of industrial engineering to this industrial engineering students. He explained this with real-life problems he solved himself. While explaining the problems one by one, he talked about problem data and then talked about what type of industrial enginerring and data science tools used. He first talked about the problem of drying timber. He talked about how he worked in harmony with forest experts on the timber drying problem. He then talked what he did while anticipating mishaps during timber drying. The second problem was about electricty markets. He mentioned how wrong forecasts cause great losses in elctricity markets, which is why accurate forecasting methods are very important. He also talked about the trendyol algorithm. Finally, he answered the questions asked by the students.

**Questions:**

**1)** What is the difference between approach to the problem between an industrial engineer who knows data science and a computer engineer?

**-Answer:** While computer engineers look at the problem more focused on data and technical aspects, industrial engineers are more inclined to get to the root of events and model the problem.

**2) Which option is not one of the shortcomings of deep learning?**

a\. need more parameters

b\. robust

c\. ability to decide

d\. data hunger

e\. lacking interpretability

# **b)**
